kind: pipeline
name: default

steps:
- name: test
  image: python:latest
  commands:
  - pip install -U pip pipenv
  - pipenv install -d
  - pipenv check
  - export VENV_HOME_DIR=$(pipenv --venv)
  - sh $VENV_HOME_DIR/bin/activate
  - sh ./bin/run-tests.sh