kind: pipeline
name: default

steps:
- name: test
  image: python:latest
  commands:
  - pip install pipenv
  - pipenv install
  - export VENV_HOME_DIR=$(pipenv --venv)
  - sh $VENV_HOME_DIR/bin/activate
  - sh ./bin/run-tests.sh